export const robots = [
  "index, follow",
  "index, nofollow",
  "noindex, follow",
  "noindex, nofollow",
];
export const charset = ["utf-8", "utf-16", "ISO-8859-1", "WINDOWS-1252"];
export const languages = [
  "en_US",
  "ar_AE",
  "zh_CN",
  "zh_TW",
  "cs_CZ",
  "da_DK",
  "in_ID",
  "ms_MY",
  "nl_NL",
  "fr_FR",
  "fi_FI",
  "de_DE",
  "it_IT",
  "ja_JP",
  "ko_KR",
  "no_NO",
  "pl_PL",
  "pt_BR",
  "ro_RO",
  "ru_RU",
  "es_ES",
  "sv_SE",
  "th_TH",
  "tl_PH",
  "tr_TR",
];
